# For wallpaper switching 
[config.wallpaper]
set = false
command = "swww"
arguments = ["img", "--transition-type", "center"]

# Hyprland
[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland-colors.conf"
output_path = "~/.config/hypr/colors.conf"
post_hook = " hyprctl reload"



# Kitty
[templates.kitty]
input_path = "~/.config/matugen/templates/kitty-colors.conf"
output_path = "~/.config/kitty/colors.conf"
post_hook = " kill -SIGUSR1 $(pgrep kitty)"


# Rofi
[templates.rofi]
input_path = "~/.config/matugen/templates/rofi-colors.rasi"
output_path = "~/.config/rofi/colors.rasi"

# Waybar
[templates.waybar]
input_path = "~/.config/matugen/templates/colors.css"
output_path = "~/.config/waybar/colors.css"
post_hook = "pkill waybar; waybar & "

# gtk
[templates.gtk3]
input_path = "~/.config/matugen/templates/matugen-gtk.css"
output_path = "~/.config/gtk-3.0/gtk.css"


[templates.gtk4]
input_path = "~/.config/matugen/templates/matugen-gtk.css"
output_path = "~/.config/gtk-4.0/gtk.css"
